export const SET_FILTER = 'SET_FILTER';
export const TOGGLE_FILTERS_COMPONENT = 'TOGGLE_FILTERS_COMPONENT';
export const SET_SELECTED_POSTS = 'SET_SELECTED_POSTS';
export const SET_POSTS_DATA = 'SET_POSTS_DATA';
