export const PAGE = {
  SET_FILTER: 'SET_FILTER',
  TOGGLE_FILTERS_COMPONENT: 'TOGGLE_FILTERS_COMPONENT',
  SET_SELECTED_POSTS: 'SET_SELECTED_POSTS',
  GET_POSTS: 'GET_POSTS',
  DELETE_POSTS: 'DELETE_POSTS',
  RESET_FETCHING_SETTINGS: 'RESET_FETCHING_SETTINGS',
};

export const POST = {
  SELECT: 'POST__SELECT',
  UPDATE: 'POST__UPDATE'
};
