export const PAGE = {
  SET_FILTER: 'PAGE__SET_FILTER',
  TOGGLE_FILTERS_COMPONENT: 'PAGE__TOGGLE_FILTERS_COMPONENT',
  SET_SELECTED_POSTS: 'PAGE__SET_SELECTED_POSTS',
  GET_POSTS: 'PAGE__GET_POSTS',
  DELETE_POSTS: 'PAGE__DELETE_POSTS',
  RESET_FETCHING_SETTINGS: 'PAGE__RESET_FETCHING_SETTINGS',
};

export const POST = {
  SELECT: 'POST__SELECT',
  UPDATE: 'POST__UPDATE'
};
