export const LOGIN_REQUEST = {
  BASE: 'LOGIN_REQUEST',
  REJECTED: 'LOGIN_REQUEST_REJECTED',
  PENDING: 'LOGIN_REQUEST_PENDING',
  FULFILLED: 'LOGIN_REQUEST_FULFILLED',
};

export const REGISTER_REQUEST = {
  BASE: 'REGISTER_REQUEST',
  REJECTED: 'REGISTER_REQUEST_REJECTED',
  PENDING: 'REGISTER_REQUEST_PENDING',
  FULFILLED: 'REGISTER_REQUEST_FULFILLED',
};
