export const LOGIN_REQUEST = {
  BASE: 'LOGIN_REQUEST',
  ERROR: 'LOGIN_REQUEST_ERROR',
  PENDING: 'LOGIN_REQUEST_PENDING',
  FULFILLED: 'LOGIN_REQUEST_FULFILLED',
};

export const REGISTER_REQUEST = {
  BASE: 'REGISTER_REQUEST',
  ERROR: 'REGISTER_REQUEST_EROOR',
  PENDING: 'REGISTER_REQUEST_PENDING',
  FULFILLED: 'REGISTER_REQUEST_FULFILLED',
};
